### ISSUE TITLE
Payload Size in Struct Packet and Frame

### ISSUE THREAD

**Issue by KewenGu** [KewenGu/CS3516-Program3#2]
When I allocate memory to a Frame struct, I found that the payload attribute is a void pointer which occupies only 4 bytes in memory, while the actual payload is 0 to 130 bytes long. This will cause problem when we want to transport the frame struct through the physical layer to the server, since the client send the memory address of a local machine instead of the object. However, if we change the type of payload to a fixed-sized array, another problem may occur. Because the frame payload size is not fixed at 130 bytes (the last frame of a packet may contain less payload), the client will send "dummy (useless) bytes" to the server. As a result, the server will have to handle these "dummy bits", which may be hard to implement. The same problem also exists with the Packet struct, since the data field is not always 256 bytes.

@mathcolo, How do you think?

If necessary, I suggest that we just use byte strings (unsigned char *) to store and buffer the packets and frames, because this would be much easier for us to control the size of the buffer and allocate memory to them.

Excuse me for my bad writing.

**Comment by mathcolo** [comment]
Very reasonable question/evaluation, my friend. I think I am led to believe this isn't a problem due to the way I am packing data for transmission. Currently my client is filling packet payloads 100% full, until the last one is not entirely filled due to n%256 > 0. The physical layer should be able to avoid sending useless bits by stopping at the end of frame indicator, and the server should be able to recognize the indicators as well. Am I missing something?

And with regards to memory allocation, I suppose limiting the length of the buffers would be better there. Given this is a simulation, I do not see that as a top priority, although I would be willing to switch to your method since I'm sure it'll work as well!

**Comment by mathcolo** [comment]
I have pondered this more, and although I believe the original solution still works (using end indicators heavily), I think you are right that using byte arrays that are not dynamically allocated is probably better. I realized that if we do it that way, we can set the structs as packed, and then send()/recv() them directly as buffers instead of having to send the frame's bytes up until the payload pointer, then dereference the payload pointer and send that part separately.

You originally mentioned that this will cause dummy bytes, but I think this is fixed by using packed structs. You can simply cast the incoming buffer to a Frame and then instantly have access to all of the necessary struct members. A loop to find the end of the payload is OK.

**Comment by KewenGu** [comment]
Yeah, make sense to me. Let's do it this way.

**Comment by mathcolo** [comment]
OK, I'll switch it on the client side
